# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        informational: true  # Don't block PRs
        target: auto
    patch:
      default:
        informational: true  # Don't block PRs
        target: auto

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
